### ISSUE TITLE
Support for Maven-2.2.1

### ISSUE THREAD

**Issue by smoradi** [mrdon/maven-trap#1]
I've installed maven-trap-0.5 in maven-2.1.0  , every things was fine and I enjoyed features a lot !

Now for some reasons(eg. AppFuse2.1) I have to use maven-2.2.1 , I've tried same settings but maven didn't came up !

I miss the features!, would you please provide patch for this issue , maven-trap is rock !;-) thanks.

Cheers,
Sid

mvn -v
Apache Maven 2.2.1 (r801777; 2009-08-07 05:16:01+1000)
Java version: 1.6.0_16
Java home: /opt/dev/SDKs/jdk1.6.0_16/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux" version: "2.6.24-25-generic" arch: "amd64" Family: "unix"

and Exception:
mvn -v
Colorizing console...
java.lang.ClassNotFoundException: org.codehaus.classworlds.Launcher
        at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:169)
        at org.twdata.maven.trap.Dispatcher.getMavenMainClass(Dispatcher.java:105)
        at org.twdata.maven.trap.Dispatcher.getMavenMainMethod(Dispatcher.java:100)
        at org.twdata.maven.trap.Dispatcher.invokeMavenMainMethod(Dispatcher.java:95)
    at org.twdata.maven.trap.Dispatcher.main(Dispatcher.java:30)
(arg: 4) 

_note: maven-2.2.1 had a below difference in mvn script 
-classpath "${M2_HOME}"/boot/classworlds-_.jar:"${M2_HOME}"/boot/maven-trap-0.5.jar \
I've tried both -cp & -classpath , result is same.

**Comment by fcuozzo** [comment]
For posterity to fix this you have to replace the classpath line with:

-classpath "${M2_HOME}"/boot/classworlds-1.1.jar:"${M2_HOME}"/boot/maven-trap-0.5.jar \

Please note the version on the classworlds.jar, previously this was using a wildcard to match any version but the expansion doesn't work when you have multiple entries on the classpath variable, so specifying the proper version fix the issue.
